<a href="https://colab.research.google.com/github/Kaisi998/Coders/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries

In [2]:
import pandas as pd # useful for loading dataset
import numpy as np # to perform array

Choose dataset from local directory

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Advertising.csv to Advertising.csv


Load Dataset

In [4]:
dataset = pd.read_csv('Advertising.csv')
print(dataset)

     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]


Summarize Dataset

In [5]:
print(dataset.shape) # no of rows and columns
print(dataset.head(5)) # top values of the data

(200, 5)
   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9


Segregate Dataset into X(Input/Independent Variable) & Y(Output/Dependent Variable)

In [9]:
X = dataset.iloc[:, :-1].values
X

array([[  1. , 230.1,  37.8,  69.2],
       [  2. ,  44.5,  39.3,  45.1],
       [  3. ,  17.2,  45.9,  69.3],
       [  4. , 151.5,  41.3,  58.5],
       [  5. , 180.8,  10.8,  58.4],
       [  6. ,   8.7,  48.9,  75. ],
       [  7. ,  57.5,  32.8,  23.5],
       [  8. , 120.2,  19.6,  11.6],
       [  9. ,   8.6,   2.1,   1. ],
       [ 10. , 199.8,   2.6,  21.2],
       [ 11. ,  66.1,   5.8,  24.2],
       [ 12. , 214.7,  24. ,   4. ],
       [ 13. ,  23.8,  35.1,  65.9],
       [ 14. ,  97.5,   7.6,   7.2],
       [ 15. , 204.1,  32.9,  46. ],
       [ 16. , 195.4,  47.7,  52.9],
       [ 17. ,  67.8,  36.6, 114. ],
       [ 18. , 281.4,  39.6,  55.8],
       [ 19. ,  69.2,  20.5,  18.3],
       [ 20. , 147.3,  23.9,  19.1],
       [ 21. , 218.4,  27.7,  53.4],
       [ 22. , 237.4,   5.1,  23.5],
       [ 23. ,  13.2,  15.9,  49.6],
       [ 24. , 228.3,  16.9,  26.2],
       [ 25. ,  62.3,  12.6,  18.3],
       [ 26. , 262.9,   3.5,  19.5],
       [ 27. , 142.9,  29.3,  12.6],
 

In [10]:
Y = dataset.iloc[:, -1].values
Y

array([22.1, 10.4,  9.3, 18.5, 12.9,  7.2, 11.8, 13.2,  4.8, 10.6,  8.6,
       17.4,  9.2,  9.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 12.5,
        5.6, 15.5,  9.7, 12. , 15. , 15.9, 18.9, 10.5, 21.4, 11.9,  9.6,
       17.4,  9.5, 12.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 12.9,
        8.5, 14.9, 10.6, 23.2, 14.8,  9.7, 11.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 15.7, 14. , 18. ,  9.3,
        9.5, 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 12.3, 11.3, 13.6, 21.7, 15.2, 12. , 16. ,
       12.9, 16.7, 11.2,  7.3, 19.4, 22.2, 11.5, 16.9, 11.7, 15.5, 25.4,
       17.2, 11.7, 23.8, 14.8, 14.7, 20.7, 19.2,  7.2,  8.7,  5.3, 19.8,
       13.4, 21.8, 14.1, 15.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 11.6, 15.2, 19.7, 10.6,  6.6,  8.8, 24.7,  9.7,  1.6, 12.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 11.4, 10.3, 13.2, 25.4, 10.9, 10.1, 16

Splitting Dataset into Train & Test

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print(X_train)

[[-0.49683826 -0.52286826 -0.60474345  0.09678234]
 [ 0.42645864  0.89568081  0.61159096  2.18119928]
 [ 1.47170041  1.18365694 -0.13172451  0.01340566]
 [-0.04390015  0.36713204 -0.15199675 -0.37895517]
 [ 0.86197605 -1.29435986  0.17235909 -0.44761832]
 [-1.31561098 -1.08578456 -0.71961948 -0.56042206]
 [-1.2110868   1.64702594  0.34129443  0.66080104]
 [ 1.05360371  0.22018125 -0.34796174  0.04773724]
 [-1.03687984  0.57570734 -0.06415038  0.09187783]
 [-0.7581487  -1.73758238  0.3277796   0.57251985]
 [ 0.54840352  1.31875685 -1.37508858  0.65099202]
 [-0.06132085  0.51763808 -1.33454409 -1.16858136]
 [ 1.41943833  0.76532125 -1.20615324 -0.11411161]
 [-1.40271446 -0.07846066  0.04396824 -0.52118598]
 [ 0.93165883  0.20596021  1.11163955  0.39105297]
 [-0.13100364  0.75584055  0.69267992  1.43571369]
 [-0.79299009  1.28912968  0.37508149 -0.67813031]
 [ 1.10586579  0.11352343  0.91567456 -1.0950137 ]
 [-0.84525218 -0.63426643 -0.92234188 -1.2813851 ]
 [-0.23552781 -0.91987239  0.28

Training

In [15]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() # loading the algorithm.
model.fit(X_train, y_train) # train

ValueError: ignored

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() # loading the alg.
model.fit(X_train, y_train) # train

In [17]:
y_pred = model.predict(X_test)

AttributeError: ignored